const HTTP_CLIENT_ERROR_NOT_FOUND = 404;
const HTTP_CLIENT_BAD_REQUEST = 400;
const HTTP_CLIENT_CONFLICT = 409;
const HTTP_CLIENT_UNAUTHORISED = 401;
const SERVERSIDE_ERROR = 500;

exports.HTTP_CLIENT_ERROR_NOT_FOUND = HTTP_CLIENT_ERROR_NOT_FOUND;
exports.HTTP_CLIENT_BAD_REQUEST = HTTP_CLIENT_BAD_REQUEST;
exports.HTTP_CLIENT_CONFLICT = HTTP_CLIENT_CONFLICT;
exports.HTTP_CLIENT_UNAUTHORISED = HTTP_CLIENT_UNAUTHORISED;
exports.SERVERSIDE_ERROR = SERVERSIDE_ERROR;
