const HTTP_CLIENT_ERROR_NOT_FOUND = 404;
const HTTP_CLIENT_BAD_REQUEST = 400;
const SERVERSIDE_ERROR = 500;

exports.HTTP_CLIENT_ERROR_NOT_FOUND = HTTP_CLIENT_ERROR_NOT_FOUND; 
exports.HTTP_CLIENT_BAD_REQUEST = HTTP_CLIENT_BAD_REQUEST;
exports.SERVERSIDE_ERROR = SERVERSIDE_ERROR;
